### ISSUE TITLE
Option to process imported CSS?

### ISSUE THREAD

**Issue by evanhuntley** [ben-eb/gulp-cssnano#20]
I have a gulp task for one of my projects which runs gulp-sass and uses gulp-minify-css.  In my main Sass file, I am importing a number of bower dependencies, some of which do not have Sass files available and have to be imported as regular CSS.

The documentation for gulp-minify-css suggests that I move to this package, as the former has been deprecated.  That said, gulp-minify-css was automatically processing the aforementioned @import rules for me and dumping the contents into the build, via the `processImport` option of clean-css. 

Is there an equivalent option or method of achieving the same in gulp-cssnano?

**Comment by ben-eb** [comment]
Not with gulp-cssnano specifically as it is just a wrapper for the cssnano module; it's really meant as a drop-in replacement for builds that don't yet rely on PostCSS. But you can replace gulp-cssnano with gulp-postcss, and then you are free to use PostCSS plugins on your CSS to achieve this task.

```js
var postcss = require('gulp-postcss');
var gulp = require('gulp');
var cssnano = require('cssnano');
var atImport = require('postcss-import');

gulp.task('css', function () {
    var processors = [
        atImport(),
        cssnano()
    ];
    return gulp.src('./src/*.css')
        .pipe(postcss(processors))
        .pipe(gulp.dest('./dest'));
});
```

https://github.com/postcss/postcss-import

Hope this helps. :smile:

*Note: I don't intend on supporting inlining `@import` rules for cssnano (via bundling postcss-import) because I don't think it fits the responsibility of a CSS minifier. In any case this distinction is only semantic as you are free to load whichever PostCSS plugins you like alongside cssnano.*

**Comment by evanhuntley** [comment]
Thanks, @ben-eb

What you recommended actually works like a charm in my Sass build when combined with gulp-if and some other goodness.  Some irony given the debate I've stumbled into between Sass and PostCSS.

**Comment by ben-eb** [comment]
Good to hear. :+1:

**Comment by Mehrajkhan** [comment]
I want to apply cssnano and autoprefixer in my css code. I read on the internet that it is enough to use cssnano, that cssnano automatically applies autoprefixer. When I use this code:

`var gulp = require('gulp');
var cssnano = require('gulp-cssnano');

gulp.task('default', function() {
return gulp.src('./....css')
    .pipe(cssnano())
    .pipe(gulp.dest('./....'));
});`

The css code is compressed but I don't see anywhere the prefixes. Does cssnano apply autoprefixer or not? Is the above code correct?

**Comment by luksak** [comment]
@Mehrajkhan This is completely off-topic.
